# Generated by Django 2.1.7 on 2019-04-18 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0005_auto_20190418_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 15, 9, 12, 395419, tzinfo=utc)),
        ),
    ]
