# Generated by Django 2.1.7 on 2019-04-21 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0006_auto_20190418_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 10, 10, 46, 448165, tzinfo=utc)),
        ),
    ]
